### ISSUE TITLE
FALTA DE SUPORTE A CODIFICAÇÃO UTF-8

### ISSUE THREAD

**Issue by r3dfouri3r** [DesignLiquido/vscode#14]
Pessoal, eu amei bastante essa extensão para o vscode, no entanto não há suporte a codificação de caracteres especiais da língua portuguesa. Tem como colocar essa feature para UTF-8?
![Captura de Ecrã (29)](https://user-images.githubusercontent.com/33198911/234078362-9fac269c-23e9-4266-bb74-e051c87a00c3.png)

**Comment by leonelsanchesdasilva** [comment]
@it-nerdoca Na verdade eu acho que este arquivo está como ISO-8859-1, que é a codificação que o VisuAlg usa. 

![image](https://user-images.githubusercontent.com/53848829/234149014-54dfcece-2deb-4bcc-a67c-ceccbbd2c85e.png)

Quando eu peço para reabrir o arquivo em ISO-8859-1:

![image](https://user-images.githubusercontent.com/53848829/234149272-d54a8cd1-b430-4f16-8912-923e5d64fa39.png)

Ele abre certinho. 

![image](https://user-images.githubusercontent.com/53848829/234149311-5f6d4553-0182-4e0c-9c1f-0312ccaa7a1e.png)

Clicando nessa opção, posso escolher salvar o arquivo em UTF-8, que é o padrão do VSCode:

![image](https://user-images.githubusercontent.com/53848829/234149452-494d538a-9efd-498e-9aa8-792283566630.png)

![image](https://user-images.githubusercontent.com/53848829/234149502-544237a3-93c8-4f9b-8358-74716f4cc376.png)

Aí o arquivo abre com a acentuação correta.

![image](https://user-images.githubusercontent.com/53848829/234149572-d30e1b5f-d104-4c6f-9db6-51a739694f88.png)

Eu não sei se vale a pena colocar algo na extensão pra isso, sendo que o VSCode já possui o recurso de recodificação de arquivos. Ninguém mais usa ISO-8859-1. É uma codificação já bem defasada.

**Comment by leonelsanchesdasilva** [comment]
Como o recurso de traduç!ao de codificação é algo mais do VSCode do que da extensão, estamos fechando a issue. Fiquem à vontade para reabrir se for o caso.
