### ISSUE TITLE
Usar no provedor de completude de FolEs uma lista que venha da biblioteca de FolEs

### ISSUE THREAD

**Issue by leonelsanchesdasilva** [DesignLiquido/vscode#15]
Hoje em dia [o provedor de completude de FolEs](https://github.com/DesignLiquido/vscode/blob/principal/fontes/completude/foles-provedor-completude.ts) usa [essa lista de sugestões](https://github.com/DesignLiquido/vscode/blob/principal/fontes/linguagens/foles/modificadores.ts), que fiz para validar o funcionamento do provedor. O problema é que a lista não vem da biblioteca, mas da própria extensão, o que pode ocasionar esforço duplo mais futuramente. 

A ideia é achar uma forma de trazer os modificadores dinamicamente de `@designliquido/foles` e popular o provedor de completude. Provavelmente isso trará impacto em FolEs também.

**Comment by VitBrandao** [comment]
Solucionado nos PRs https://github.com/DesignLiquido/vscode/pull/26 e https://github.com/DesignLiquido/vscode/pull/29
