### ISSUE TITLE
Bug no "escreval"

### ISSUE THREAD

**Issue by Montycaio** [DesignLiquido/vscode#21]
### Bom dia!

Durante meus estudos, notei um bug ao utilizar a função "**escreval**".

Ao executar a programação com o "**escreval**" a frase some e aparece apenas ">" _(Primeira imagem)_

Ao executar a programação com o "**escreva**" a frase aparece normalmente. _(Segunda imagem)_

![image](https://github.com/DesignLiquido/vscode/assets/134021684/7468f807-2fc7-4091-a7c5-ec9e15acabf9)

![image](https://github.com/DesignLiquido/vscode/assets/134021684/34862bd2-7b41-4e50-9569-3766f1dc1f7f)

Agradeço por disponibilizar uma extensão tão incrivel, espero estar contribuindo, um grande abraço!

**Comment by samuelrvg** [comment]
Boa tarde! @Montycaio, obrigado pelo report, mais tarde eu já devo subir uma correção e te aviso por aqui.
