### ISSUE TITLE
Auto-completar para VisuAlg

### ISSUE THREAD

**Issue by leonelsanchesdasilva** [DesignLiquido/vscode#23]
Base: https://www.youtube.com/watch?v=w5ZpAqt2L6Q&lc=Ugwcyh7isafq5tjCl0R4AaABAg

O que já temos: https://github.com/DesignLiquido/vscode/blob/principal/fontes/documentacao-em-editor/visualg-documentacao-em-editor.ts e https://github.com/DesignLiquido/vscode/blob/principal/fontes/completude/visualg-provedor-completude.ts
O que precisa ser feito: colocar exemplos de código em https://github.com/DesignLiquido/vscode/blob/principal/fontes/primitivas/dialetos/visualg.ts e testar a extensão. 
Problema: os manuais para cada função desapareceram da internet. Vamos precisar ser criativos aqui e recriar os exemplos.

**Comment by samuelrvg** [comment]
@VitBrandao Quando fizer, adiciona uma propriedade a mais, chamada `exemploCodigo` veja como exemplo https://github.com/DesignLiquido/vscode/blob/principal/fontes/primitivas/primitivas-texto.ts

**Comment by VitBrandao** [comment]
Issue solucionada no PR https://github.com/DesignLiquido/vscode/pull/30
