### ISSUE TITLE
Traduzir tags da linguagem LMHT

### ISSUE THREAD

**Issue by leonelsanchesdasilva** [DesignLiquido/vscode#3]
Arquivos: 

- `configuracoes\configuracao-lmht.json`
- `syntaxes\lmht.tmLanguage.json`
- 
Usar como base o projeto https://github.com/DesignLiquido/LMHT.

**Comment by VitBrandao** [comment]
@leonelsanchesdasilva 
Lista de tags presentes no json sem correspondências em LMHT:
### **lmht.tmLanguage.json - linhas: 2128 e 2151**
- `adress`
- `caption`
- `figcaption`
- `footer`
- `header`
- `hgroup`
- `output`
- `slot`
- `tfoot`
- `th`
- `thead`


### **configuracao-lmht.json - linhas: 38, 45 e 52** 
- `base`
- `embed`
- `keygen`
- `menuitem`
- `meta`
- `param`
-  `source`
-  `track`

OBS.: Acredito que `embed` e `meta` sejam grupos de tags, mas mesmo assim, cito elas para saber por qual termo LMHT devo substitui-los no json.

**Comment by leonelsanchesdasilva** [comment]
- `address`: https://github.com/DesignLiquido/LMHT/blob/principal/lmht.xslt#L641
- `caption`: https://github.com/DesignLiquido/LMHT/blob/principal/lmht.xslt#L1449
- `figcaption`: https://github.com/DesignLiquido/LMHT/blob/principal/lmht.xslt#L709
- `footer`: (vou criar uma issue)
- `header`: https://github.com/DesignLiquido/LMHT/blob/principal/lmht.xslt#L521
- `hgroup`: (vou criar uma issue)
- `output`: (vou criar uma issue)
- `slot`: (vou criar uma issue)
- `tfoot`: https://github.com/DesignLiquido/LMHT/blob/principal/lmht.xslt#L1444
- `th`: https://github.com/DesignLiquido/LMHT/blob/principal/lmht.xslt#L1395
- `thead`: https://github.com/DesignLiquido/LMHT/blob/principal/lmht.xslt#L1385

**Comment by VitBrandao** [comment]
Issue solucionada no PR https://github.com/DesignLiquido/vscode/pull/24
