### ISSUE TITLE
Assinaturas de métodos da biblioteca global de Delégua

### ISSUE THREAD

**Issue by leonelsanchesdasilva** [DesignLiquido/vscode#32]
Por causa de https://github.com/DesignLiquido/vscode/blob/principal/fontes/assinaturas-metodos/delegua-provedor-assinaturas-metodos.ts, teremos que expandir os métodos da biblioteca global. 

Atualmente coloquei só um como exemplo, que é o `escreva`. Agora temos o seguinte:

```js
import { PrimitivaOuMetodo } from "./tipos";

export const metodosBibliotecaGlobal: PrimitivaOuMetodo[] = [
    {
        nome: 'escreva',
        assinaturas: [
            {
                formato: 'escreva(...argumentos: qualquer)',
                parametros: [
                    {
                        nome: '...argumentos',
                        documentacao:
                            'Os argumentos para impressão, que podem ser literais, constantes ou variáveis de qualquer tipo.',
                    },
                ],
            },
        ],
        documentacao:
            'Escreve um ou mais argumentos na saída padrão da aplicação. \n' +
            '## Interpolação \n' +
            'Delégua suporta interpolação de variáveis: \n \n' +
            "```var comidaFavorita = 'strogonoff'```\n\n" +
            '```escreva("Minha comida favorita é ${comidaFavorita}")```',
        exemploCodigo: 'função escreva(...argumentos)',
    },
    ...
```

A ideia é adicionar para os demais métodos o _array_ de assinaturas.

**Comment by Danguya** [comment]
@leonelsanchesdasilva Reparei o arquivo de tipagem fontes/primitivas/tipos.ts de PrimitivaOuMetodo, mas parece que está tudo tipado, será que pode ser mais claro acerca desta issue?

**Comment by leonelsanchesdasilva** [comment]
> @leonelsanchesdasilva Reparei o arquivo de tipagem fontes/primitivas/tipos.ts de PrimitivaOuMetodo, mas parece que está tudo tipado, será que pode ser mais claro acerca desta issue?

Olá, @Danguya. Bem-vindo!

A ideia é terminar este arquivo com as demais funções da nossa biblioteca, que estão descritas aqui: https://github.com/DesignLiquido/delegua/wiki/Fun%C3%A7%C3%B5es-nativas, mais as funções de entrada e saída, que estão aqui: https://github.com/DesignLiquido/delegua/wiki/Entrada-e-Sa%C3%ADda.

**Comment by Danguya** [comment]
@leonelsanchesdasilva Entendi, acabei de abrir uma PR #56  para esta issue, por favor dê uma revisada.

**Comment by leonelsanchesdasilva** [comment]
Resolvido em https://github.com/DesignLiquido/vscode/pull/56.
