### ISSUE TITLE
Implementar `limpatela` - VisuAlg

### ISSUE THREAD

**Issue by samuelrvg** [DesignLiquido/vscode#36]
Relacionado: https://github.com/DesignLiquido/delegua/issues/502

https://stackoverflow.com/a/41600891/9043143

Evento que deve ser criado na classe `DeleguaSessaoDepuracaoBase`:
```
this.tempoExecucao.on('limpatela', () => {        
    vscode.commands.executeCommand('workbench.debug.panel.action.clearReplAction');
});
```

**Comment by leonelsanchesdasilva** [comment]
Uma tentativa de suporte à `limpatela` foi implementada na versão 0.11.1 da extensão. No entanto, só funciona quando há um evento de parada, o que força o VSCode atualizar todos os componentes. Para execuções contínuas, o comando simplesmente não funciona. Isso se deve à natureza do console de depuração. 

Nossa próxima abordagem deve ser implementar um novo painel de entrada e saída do programa sendo executado, que não usa nem o console de depuração, nem o terminal.

**Comment by leonelsanchesdasilva** [comment]
Com o novo painel de Entrada e Saída, implementado na versão 0.12.0, mais os mecanismos de resolução de condição de corrida implementados nas versões posteriores da extensão, podemos considerar essa issue como resolvida.
