### ISSUE TITLE
melhoria no fluxo de execução/depuração

### ISSUE THREAD

**Issue by igorriqzzin** [DesignLiquido/vscode#54]
Quando vc executa o programa mais não esta com o terminal na aba de debug console, ele tem deveria abrir o terminal na aba de debug console para o usuário poder ver o resultado.

Como reproduzir : executar / depurar arquivo sem estar com a aba do terminal aberta.

**Comment by leonelsanchesdasilva** [comment]
Olá, @igorriqzzin 👋 

Obrigado pela sugestão. Creio ser possível fazer emitindo um comando para sempre exibir o debug console (a mesma ideia de https://github.com/DesignLiquido/vscode/issues/36).

**Comment by leonelsanchesdasilva** [comment]
Conforme apurado em https://github.com/DesignLiquido/vscode/issues/60 e https://github.com/DesignLiquido/vscode/issues/36, o console de depuração possui baixa vocação para ser também a entrada e a saída do problema. Vamos implementar um novo painel de entrada e saída na extensão, o que resolve o problema reportado aqui.

**Comment by leonelsanchesdasilva** [comment]
Com o novo painel de Entrada e Saída, implementado na versão 0.12.0, mais os mecanismos de resolução de condição de corrida implementados nas versões posteriores da extensão, podemos considerar essa issue como resolvida.
