### ISSUE TITLE
Problema ao executar Escreva antes do Leia

### ISSUE THREAD

**Issue by jpparella** [DesignLiquido/vscode#62]
Quando executado o comando Escreva antes do Leia acontece um problema de mostrar a mensagem do escreva depois do texto do leia:

![image](https://github.com/DesignLiquido/vscode/assets/47798178/c9f4b238-89dd-4fe3-92a6-fcff6a5f408f)

**Comment by leonelsanchesdasilva** [comment]
Oi, @jpparella 👋 

Obrigado pela issue. Parece haver uma condição de corrida entre `escreva` (que usa `setImmediate`, e libera o _event loop_ do Node), e `leia`, que até então não estava usando.

A versão 0.12.7 deve ter isso corrigido.
