### ISSUE TITLE
Utilização da extensão

### ISSUE THREAD

**Issue by ghost** [DesignLiquido/vscode#63]
Olá, espero que esteja tudo bem por aí. Preciso de ajuda para rodar a extensão. Estou iniciando meus estudos em programação... não estou conseguindo executar a extensão devido os erros que vou deixar em anexo.

![Erro Método não implementado](https://github.com/DesignLiquido/vscode/assets/163618634/74449f60-8af4-42ce-8fa5-b752df49c441)

**Comment by leonelsanchesdasilva** [comment]
Olá, @nissoladev 👋 

Obrigado por reportar o problema. Por favor, atualize sua extensão para a versão 0.12.9 e teste novamente.

**Comment by ghost** [comment]
Olá @leonelsanchesdasilva. Vocês são incríveis. Muito obrigado por resolverem o problema de modo tão rápido. Abração para toda a equipe.
