### ISSUE TITLE
Problema na depuração do VSCode

### ISSUE THREAD

**Issue by jpparella** [DesignLiquido/vscode#64]
Ao tentar executar um código em modo depuração, não aparece a depuração no VSCode

```js
var n1 = 0;
var n2 = 0;

var n1 = leia("digite a nota 1 ");
var n2 = leia("digite a nota 2 ");

var media = (n1+n2)/2;

se (media >= 7){
    escreva("sua média foi "+media+ " parabens, voce foi aprovado")

}
senao se(media>=5 e media <7){
    escreva("sua média foi "+media+ " voce esta de recuperação")
}
senao{
    escreva("sua média foi "+media+ " voce esta reprovado")
}
```

Testei com outros códigos e o erro se repete

Na tela apresenta o erro no callstack
![image](https://github.com/DesignLiquido/vscode/assets/47798178/02372466-4771-43f1-9bca-5633ba0e1779)

**Comment by leonelsanchesdasilva** [comment]
Oi, @jpparella 👋 

Obrigado por reportar. Erro meu que refatorei uma parte do código errado. 

A versão 0.12.10 corrige este problema. Só aguardar o VSCode atualizar sozinho.
